### ISSUE TITLE
run.sh errors

### ISSUE THREAD

**Issue by dougbtv** [QXIP/homer-docker#1]
Trying to run the docker image, and I'm running into an issue with `run.sh`

``` bash
root@990687fc3cfb:/# ./run.sh 
./run.sh: 87: [: 127.0.0.1: unexpected operator
./run.sh: 131: ./run.sh: 2: not found
```

I've forked it and I'll make a PR if I can chase it down. (Also I recognize some of the lines from my own run.sh in my dougbtv/docker-asterisk project! @ https://github.com/dougbtv/docker-asterisk/blob/master/high-availability/homer/webapp/run.sh -- makes it easy for me to understand! glad it could be of reference)

**Comment by lmangani** [comment]
Hi @dougbtv 
Are you running with defaults or with parameters?

The run.sh is a mixture of influences and although I apparently copied a copy myself, I'm happy you flew back into it - higher the chance of helping with it ;)

**Comment by dougbtv** [comment]
I pulled it from dockerhub, and then ran per the readme a la:

```
docker run -tid --name homer5 -p 80:80 -p 9060:9060 qxip/homer-docker
```

But, was having issues alternatively with an empty kamailio.cfg and/or mysql issues it looked like...  So I started running it interactively...

```
docker run -tid --name homer5 -p 80:80 -p 9060:9060 --entrypoint=/bin/bash qxip/homer-docker
```

And that's what I'm getting. No params though just `./run.sh` inside the container

hahah, doesn't hurt! seriously, no i'm glad to have any influence. I love homer, but, I love it even more in docker, got excited when I noticed there was an official docker image for it!

I'm trying to build an image now from a fork and see if I can patch anything up there.

**Comment by lmangani** [comment]
pushed a minor change to hopefully fix this around could you try again please?

**Comment by dougbtv** [comment]
sure thing, pulling it down / building / running now...

**Comment by dougbtv** [comment]
brilliant! I think that works perfectly, or looks wicked good when I run `run.sh` interactively.

pasted the results here: http://www.pasteall.org/63215

previously I wasn't seeing it go through the mysql bootstrap process etc. Likely this closes it!

This is probably another issue, but, while you're around -- Do you have any recommendation for how I might mount a persistent volume for mysql data into the container? Like... 

```
docker run -tid --name homer5 -v /some/local/path:/var/lib/mysql -p 80:80 -p 9060:9060 qxip/homer-docker
```

Do you think that volume mount will work?

**Comment by lmangani** [comment]
I'm not really a Docker expert but it should work to my knowledge. Let's keep this open to make sure everything works including the mount. And THANKS a bunch for your help moving this forward!

**Comment by dougbtv** [comment]
Thank you @lmangani !! No prob, happy to help & thank you too for your help jumping on the script, and excited to have homer wrapped up nicely in Docker, I think it'll be ideal.

Didn't have a lot more time this afternoon, but, planning on taking a look tomorrow to make sure I'm getting data and it's coming through to the webapp before I close out the issue.

I'm taking a look at the database persistence too. I think the clean way will be to add a conditional in the block labeled `# MYSQL SETUP` (https://github.com/QXIP/homer-docker/blob/master/run.sh#L83-L89) to look for some kind of semaphore to check that the data structures exist, and in that case to not run the SQL scripts. When I get there, I'll make a PR with it and an updated doc.

**Comment by lmangani** [comment]
Thanks @dougbtv and looking forward your PR
