### ISSUE TITLE
Defaut login/password

### ISSUE THREAD

**Issue by therebel226** [QXIP/homer-docker#3]
Hello,

sorry but what is default login / password for Homer web interface ?

Thanks

**Comment by therebel226** [comment]
OK found it in SQL file !

admin / test123
noc / 123test

**Comment by lmangani** [comment]
All details are available on the project wiki http://github.com/sipcapture/homer/wiki

**Comment by crawc** [comment]
The "default credentials" (https://github.com/sipcapture/homer-api/blob/master/sql/schema_configuration.sql#L159) link found on this wiki page (https://github.com/sipcapture/homer/wiki/Using-Homer-5) is broken.

     HOMER UI:
         [default: admin/test1234]
