### ISSUE TITLE
"I see search results, but when i click on a message it shows an empty window"

### ISSUE THREAD

**Issue by maddimon** [QXIP/homer-docker#5]
Hello!
On the FAQ page there is an answer that on kamailio > 4.3 need to be uncomment next line:
`$var(a) = $var(table) + "%Y%m%d";`
, but last pull from docker hub kamailio is 4.3.4
`version: kamailio 4.3.4 (x86_64/linux)`
run.sh have next line:
`sed -i -e 's/$var(a) = $var(table) + "_%Y%m%d";/# runscript removed -- $var(a) = $var(table) + "_%Y%m%d";/' $PATH_KAMAILIO_CFG`
So, i'm trying to fix the problem with "empty window".

**Comment by dougbtv** [comment]
If you have search results in the UI, then kamailio was able to insert something into the database that the Homer front-end could read out. So, I think the kamailio config is at least OK enough to get data into the db.

...Have you checked the HTTP logs to see if any errors crop up there?

**Comment by lmangani** [comment]
we fixed a couple minor bugs potentially related, will rebuild the image

**Comment by maddimon** [comment]
Sorry. My mistake. Forgot about http logs...
There is new lines appear after click on a message.
`[Mon Feb 15 18:36:03.486481 2016] [:error] [pid 133] [client 192.168.1.8:55830] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Search.php on line 678, referer: http://192.168.1.6/
[Mon Feb 15 18:36:03.491966 2016] [:error] [pid 135] [client 192.168.1.8:55831] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 74, referer: http://192.168.1.6/
[Mon Feb 15 18:36:03.493245 2016] [:error] [pid 134] [client 192.168.1.8:55832] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 184, referer: http://192.168.1.6/
[Mon Feb 15 18:36:03.494482 2016] [:error] [pid 132] [client 192.168.1.8:55833] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 277, referer: http://192.168.1.6/`

And about searching results in the UI - not everything goes smoothly. Have some bug with time/timestamp. First of all docker container have UTC (without timezone) and in preferences.php set Amsterdam default timezone.

**Comment by lmangani** [comment]
I am in Amsterdam too so its not timezone related :)
Could you try pull the latest image (unless you build your own) and test again? Thanks for your report!

**Comment by maddimon** [comment]
With latest image there is no problem with searching now but problem with message persist.
When I click on CallID
`[Mon Feb 15 19:36:46.342414 2016] [:error] [pid 216] [client 192.168.1.8:56463] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 74, referer: http://192.168.1.6/
[Mon Feb 15 19:36:46.360512 2016] [:error] [pid 217] [client 192.168.1.8:56464] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 184, referer: http://192.168.1.6/
[Mon Feb 15 19:36:46.520247 2016] [:error] [pid 218] [client 192.168.1.8:56461] PHP Notice:  Undefined index: node in /var/www/html/api/RestApi/Report.php on line 277, referer: http://192.168.1.6/`
and message is empty

**Comment by dougbtv** [comment]
:+1: I might have sent you on the wrong path @maddimon -- I think those notices can be ignored, I assumed something in the UI but Lorenzo actually knew what was going on.

**Comment by lmangani** [comment]
We better document the node configuration on the [wiki](https://github.com/sipcapture/homer/wiki/Using-DB-Nodes) while I try replicate this issue. Kamailio 4.4 should put an end to this glitch and its workarounds.

**Comment by maddimon** [comment]
In the admin panel there is everything looks fine with node configuration (except "DB Tables" -homer_statistic).  There is only one node.
And when I select Quick Search in the search results in column node:
`homer01:2001`

**Comment by lmangani** [comment]
Any node(s) listed in ADMIN will not be relevant unless you disable the `SINGLE_NODE` option
